services:
  web:
    build: ./pikpak-plus-client
    depends_on:
    - server
    ports:
      - '3002:3002'
      - '3001:3001'
    volumes:
    - ./pikpak-plus-client:/user/src/app
    env_file:
    - ./.env
  server:
    build: ./pikpak-plus-server
    ports:
    - '5000:5000'
    volumes:
    - ./pikpak-plus-server:/app
    env_file:
    - ./.env
